name: Nightly build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Collect docker meta
        id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: madpeteguy/jenkins-docker-slave-ssh
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to DockerHub
        #        if: github.event_name == 'release' && github.event.action == 'created' || github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push nightly docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          #          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          push: true
          tags: madpeteguy/jenkins-docker-slave-ssh:nightly
          labels: ${{ steps.docker-metadata.outputs.labels }}
